//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEğitimlerim
    {
        public int Id { get; set; }
        [StringLength(100,ErrorMessage ="En fazla 100 karakter olmalıdır")]
        [Required(ErrorMessage ="Bu alanı boş geçemezsiniz!")]
        public string Baslik { get; set; }
        public string AltBaslik { get; set; }
        public string AltBaslik2 { get; set; }
        [StringLength(10, ErrorMessage = "En fazla 10 karakter olmalıdır")]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz!")]
        public string GNO { get; set; }
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz!")]
        public string Tarih { get; set; }
    }
}
